config/routes.rb
Rails.application.routes.draw do
  root to: 'albums#index'
  resources :albums do 
    resources :songs
  end 

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  scope :rock, -> { where(genre: "Rock") }
  has_many :album_artists
  has_many :artists, :through => :album_artists
  # has_and_belongs_to_many(:artists)
  has_many :songs, dependent: :destroy
  validates :name, presence: true
  validates_length_of :name, maximum: 100

  before_save(:titleize_album)

  private
    def titleize_album
      self.name = self.name.titleize 
    end
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
  belongs_to :artist
  belongs_to :album
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :album_artists
  has_many :albums, :through => :album_artists
end

 

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord 
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self_authenticate(email, password)
    user = User.find_by "email = ?", email 
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else 
      nil
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save 
      flash[:notice] = "Album Saved friendo!"
      redirect_to albums_path
    else
      render :new
    end
  end

def edit
  @album = Album.find(params[:id])
  render :edit
end

def show
  @album = Album.find(params[:id])
  render :show
end

def update
  @album = Album.find(params[:id])
  if @album.update(album_params)
    redirect_to albums_path
  else
    render :edit
  end
end

def destroy
  @album = Album.find(params[:id])
  if @album.destroy 
    flash[:notice] = "You decided to DESTROY #{@album.name}"
    redirect_to albums_path
  else
    flash[:notice] = "Probably for the best you didn't destroy that"
    redirect_to albums_path
  end
end

  private 
    def album_params
      params.require(:album).permit(:name, :genre)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController 
  def new 
    @album = Album.find(params[:album_id])
    @song = @album.songs.new
    render :new
  end

  def create 
    @album = Album.find(params[:album_id])
    @song = @album.songs.new(song_params)
    if @song.save
      redirect_to album_path(@album)
    else 
      render :new
    end
  end

  def show
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    render :edit
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to album_path(@song.album)
    else
      render :edit
    end
   end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to album_path(@song.album)
  end

  private 
    def song_params
      params.require(:song).permit(:name, :lyrics)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<%= render "layouts/album_form" %>

<p><%= link_to "Return to albums", albums_path %></p>

app/views/albums/index.html.erb
<%= image_tag "rec_store.jpg" %>

<h1>Rails Record Store</h1>
<h2>Available Albums</h2>

<% if @albums.any? %>
  <ul> 
    <% @albums.each do |album|  %>
      <li><%= link_to album.name, album_path(album) %></li>  
    <% end %>
  </ul>
<% else %>
  <p>There are no albums yet.</p>
<% end %>

<p><%= link_to "Create new album", new_album_path %></p>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "layouts/album_form" %>

<p><%= link_to "Return to albums", albums_path %></p>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h3><%= @album.genre %></h3>

<% if @album.songs.any? %>
  <h4>Here are the songs for this album:</h4>

  <% @album.songs.each do |song| %>
    <ul>
      <li>
        <%= link_to song.name, album_song_path(@album, song) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No songs are listed for this album.</p>
<% end %>

<p><%= link_to "Add a song", new_album_song_path(@album) %></p>

<p><%= link_to "Edit", edit_album_path(@album) %></p>
<p><%= link_to "Delete", album_path(@album), :data => {:confirm => "U sure bro?", :method => "delete"} %></p>

<p><%= link_to "Return to albums", albums_path %></p>

app/views/layouts/_album_form.html.erb
<%= render "layouts/errors", :object => @album %>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3> Please fix these errors: </h3>
  <ul> 
  <% object.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecordStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ="box">
      <%= flash[:notice] %>
      <%= flash[:alert] %>

      <%= yield %>

    </div>
  </body>
  <footer>Jozy and Allison 4 eva (c) 2020</footer>
</html>

app/views/songs/edit.html.erb
<h1> Edit song: </h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p> <%= f.submit %></p>
<% end %>

<p><%= link_to "Return to album", album_path(@album)%></p>

app/views/songs/new.html.erb
<h1>Add a new song: </h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p> <%= f.submit %> </p>
<% end %>

<p><%= link_to "Return to album", album_path(@album)%></p>

app/views/songs/show.html.erb
<h1> Song: <%= @song.name %> </h1>
<h2> Album: <%= @album.name %></h2>
<h3><%= @song.lyrics%></h3>

</p>
<p><%= link_to "Delete song", album_song_path(@album, @song),
                          :data => {:confirm => "U sure bro?",
                                        :method => "delete"} %></p>

<p><%= link_to "Return to album", album_path(@album)%></p>